SET @HOUR := -1;

SELECT (@HOUR := @HOUR + 1) AS HOUR,
(SELECT COUNT(ANIMAL_ID) FROM ANIMAL_OUTS WHERE @HOUR = HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23

-- 실패 코드
-- SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
-- FROM ANIMAL_OUTS
-- GROUP BY HOUR(DATETIME)
-- ORDER BY HOUR