SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SALES) AS TOTAL_SALES
FROM AUTHOR AS A INNER JOIN BOOK AS B ON A.AUTHOR_ID = B.AUTHOR_ID INNER JOIN BOOK_SALES AS C ON B.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC