SELECT B.APNT_NO, C.PT_NAME, C.PT_NO, B.MCDP_CD, A.DR_NAME, B.APNT_YMD
FROM DOCTOR AS A INNER JOIN APPOINTMENT AS B ON A.DR_ID = B.MDDR_ID INNER JOIN PATIENT AS C ON B.PT_NO = C.PT_NO
WHERE B.APNT_YMD LIKE '2022-04-13%' AND B.MCDP_CD = 'CS' AND B.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD